// <auto-generated />
using System;
using MedcenterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedcenterApi.Migrations
{
    [DbContext(typeof(MedcenterDbContext))]
    [Migration("20190924161113_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MedcenterApi.Data.Model.MedcenterAppSetting", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Value")
                        .HasMaxLength(100);

                    b.HasKey("Name");

                    b.ToTable("MedcenterAppSettings");

                    b.HasData(
                        new
                        {
                            Name = "WhatsApp",
                            Value = ""
                        },
                        new
                        {
                            Name = "Phone",
                            Value = ""
                        },
                        new
                        {
                            Name = "Address",
                            Value = ""
                        },
                        new
                        {
                            Name = "CNPJ",
                            Value = ""
                        },
                        new
                        {
                            Name = "CompanyName",
                            Value = ""
                        },
                        new
                        {
                            Name = "TechinicalManager",
                            Value = ""
                        });
                });

            modelBuilder.Entity("MedcenterApi.Data.Model.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsSchedulable");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MedcenterApi.Data.Model.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin.medcenter",
                            Password = "Medcenter@dmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
