// <auto-generated />
using System;
using MedcenterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedcenterApi.Migrations
{
    [DbContext(typeof(MedcenterDbContext))]
    partial class MedcenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MedcenterApi.Data.Model.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsSchedulable");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSchedulable = true,
                            Name = "acupuntura",
                            Price = 90.00m,
                            Type = "Specialty"
                        });
                });

            modelBuilder.Entity("MedcenterApi.Data.Model.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin.medcenter",
                            Password = "Medcenter@dmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
